world_cities_data = {
    "Tokyo": {"country": "Japan", "population": 37036},
    "Delhi": {"country": "India", "population": 34665},
    "Shanghai": {"country": "China", "population": 30482},
    "Dhaka": {"country": "Bangladesh", "population": 24652},
    "Cairo": {"country": "Egypt", "population": 23074},
    "Sao Paulo": {"country": "Brazil", "population": 22990},
    "Mexico City": {"country": "Mexico", "population": 22752},
    "Beijing": {"country": "China", "population": 22596},
    "Mumbai": {"country": "India", "population": 22089},
    "Osaka": {"country": "Japan", "population": 18921},
    "Chongqing": {"country": "China", "population": 18171},
    "Karachi": {"country": "Pakistan", "population": 17598},
    "Istanbul": {"country": "Turkey", "population": 16000},
    "Lagos": {"country": "Nigeria", "population": 15942},
    "Buenos Aires": {"country": "Argentina", "population": 15582},
    "Kolkata": {"country": "India", "population": 15333},
    "Kinshasa": {"country": "DR Congo", "population": 14970},
    "Guangzhou": {"country": "China", "population": 14500},
    "Manila": {"country": "Philippines", "population": 14451},
    "Rio de Janeiro": {"country": "Brazil", "population": 13783},
    "Tianjin": {"country": "China", "population": 13391},
    "Moscow": {"country": "Russia", "population": 13197},
    "Lahore": {"country": "Pakistan", "population": 13004},
    "Shenzhen": {"country": "China", "population": 12831},
    "Bangkok": {"country": "Thailand", "population": 12000},
    "Paris": {"country": "France", "population": 11142},
    "London": {"country": "UK", "population": 10979},
    "Bogota": {"country": "Colombia", "population": 10776},
    "Ho Chi Minh City": {"country": "Vietnam", "population": 10380},
    "Jakarta": {"country": "Indonesia", "population": 10250},
    "Chennai": {"country": "India", "population": 10000},
    "Lima": {"country": "Peru", "population": 9970},
    "Chicago": {"country": "USA", "population": 9500},
    "Tehran": {"country": "Iran", "population": 9033},
    "Essen": {"country": "Germany", "population": 8800},
    "Boston": {"country": "USA", "population": 8700},
    "Baghdad": {"country": "Iraq", "population": 8600},
    "Hyderabad": {"country": "India", "population": 8098},
    "Washington D.C.": {"country": "USA", "population": 7800},
    "Barcelona": {"country": "Spain", "population": 5575},
    "Toronto": {"country": "Canada", "population": 6500},
    "Santiago": {"country": "Chile", "population": 6900},
    "Madrid": {"country": "Spain", "population": 6700},
    "Riyadh": {"country": "Saudi Arabia", "population": 6000},
    "Singapore": {"country": "Singapore", "population": 5975},
    "Marseille": {"country": "France", "population": 1760},
    "Athens": {"country": "Greece", "population": 3050},
    "Sydney": {"country": "Australia", "population": 5400},
    "Kabul": {"country": "Afghanistan", "population": 5000},
    "Casablanca": {"country": "Morocco", "population": 4180}
}

world_cities = [
    'Tokyo',
    'Delhi',
    'Shanghai',
    'Dhaka',
    'Cairo',
    'Sao Paulo',
    'Mexico City',
    'Beijing',
    'Mumbai',
    'Osaka',
    'Chongqing',
    'Karachi',
    'Istanbul',
    'Lagos',
    'Buenos Aires',
    'Kolkata',
    'Kinshasa',
    'Guangzhou',
    'Manila',
    'Rio de Janeiro',
    'Tianjin',
    'Moscow',
    'Lahore',
    'Shenzhen',
    'Bangkok',
    'Paris',
    'London',
    'Bogota',
    'Ho Chi Minh City',
    'Jakarta',
    'Chennai',
    'Lima',
    'Chicago',
    'Tehran',
    'Essen',
    'Boston',
    'Baghdad',
    'Hyderabad',
    'Washington D.C.',
    'Barcelona',
    'Toronto',
    'Santiago',
    'Madrid',
    'Riyadh',
    'Singapore',
    'Marseille',
    'Athens',
    'Sydney',
    'Kabul',
    'Casablanca',
]